# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

FROM gentoo/stage3:amd64-nomultilib-openrc
ARG compiler_kind=clang
ARG compiler_version=20.1.7
RUN /bin/bash <<"EOF"
    set -eux
    echo 'BINPKG_FORMAT="gpkg"' >> /etc/portage/make.conf
    echo 'FEATURES="getbinpkg"' >> /etc/portage/make.conf
    emerge-webrsync
    getuto
    echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf
    echo "=dev-build/cmake-4.0.3" >> /etc/portage/package.unmask
    emerge =dev-build/cmake-4.0.3
    emerge dev-build/ninja
    emerge dev-vcs/git
    emerge dev-util/gcovr
    if [[ ${compiler_kind} == clang ]] ; then
      use_params=''
      case ${compiler_version%%.*} in
        17)
          emerge =dev-lang/python-3.12.11
          use_params=python_single_target_python3_12 ;;
      esac
      echo ">llvm-runtimes/openmp-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvm-common-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-runtimes/compiler-rt-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-runtimes/compiler-rt-sanitizers-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvm-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvmgold-${compiler_version%%\.*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvm-toolchain-symlinks-${compiler_version%%\.*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/clang-common-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/clang-runtime-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      USE="libcxx $use_params" emerge =llvm-core/clang-${compiler_version}
      ln -s /usr/lib/llvm/${compiler_version%%.*}/bin/* /usr/local/bin/
    elif [[ ${compiler_kind} == gcc ]] ; then
      emerge --getbinpkgonly =sys-devel/gcc-${compiler_version}
      eselect gcc set x86_64-pc-linux-gnu-${compiler_version%%\.*}
    else
      exit 1
    fi
    rm -rf /var/db/repos/gentoo /var/cache/*
EOF
