# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

FROM gentoo/stage3:amd64-nomultilib-openrc
ARG compiler_kind=clang
ARG compiler_version=20.1.7
ARG stdlib_version=${compiler_version}
RUN /bin/bash <<-EOF
    set -eux
    echo 'BINPKG_FORMAT="gpkg"' >> /etc/portage/make.conf
    echo 'FEATURES="getbinpkg"' >> /etc/portage/make.conf
    emerge-webrsync
    getuto
    echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf
    echo "=dev-build/cmake-4.0.3" >> /etc/portage/package.unmask
    emerge =dev-build/cmake-4.0.3
    emerge dev-build/ninja
    emerge dev-vcs/git
    if [[ ${compiler_kind} == clang ]] ; then
      emerge --getbinpkgonly =llvm-core/clang-${compiler_version}
      USE="libcxx" emerge =llvm-core/clang-runtime-${stdlib_version}
      ln -s /usr/lib/llvm/${compiler_version%%.*}/bin/* /usr/local/bin/
    elif [[ ${compiler_kind} == gcc ]] ; then
      emerge --getbinpkgonly =sys-devel/gcc-${compiler_version}
      eselect gcc set x86_64-pc-linux-gnu-${compiler_version%%\.*}
    else
      exit 1
    fi
    rm -rf /var/db/repos/gentoo /var/cache/*
EOF
