# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

ARG BASE_IMAGE=gentoo/stage3:amd64-nomultilib-openrc
FROM ${BASE_IMAGE}

ARG compiler_kind=clang
ARG compiler_version=20.1.7
RUN /bin/bash <<"EOF"
    set -eux
    echo 'BINPKG_FORMAT="gpkg"' >> /etc/portage/make.conf
    echo 'FEATURES="getbinpkg"' >> /etc/portage/make.conf
    emerge-webrsync
    getuto
    case $(uname -m) in
        x86_64)   GENTOO_ARCH=amd64; GCC_TRIPLET=x86_64-pc-linux-gnu ;;
        aarch64)  GENTOO_ARCH=arm64; GCC_TRIPLET=aarch64-unknown-linux-gnu ;;
        *)        echo "Unsupported arch: $(uname -m)"; exit 1 ;;
    esac
    echo "ACCEPT_KEYWORDS=\"~${GENTOO_ARCH}\"" >> /etc/portage/make.conf
    echo "=dev-build/cmake-4.2.3" >> /etc/portage/package.unmask
    mkdir -p /etc/portage/package.accept_keywords
    echo "dev-util/gcovr **" >> /etc/portage/package.accept_keywords/gcovr
    emerge =dev-build/cmake-4.2.3
    emerge dev-build/ninja
    emerge dev-vcs/git
    emerge dev-util/gcovr
    emerge app-misc/jq
    if [[ ${compiler_kind} == clang ]] ; then
      use_params=''
      case ${compiler_version%%.*} in
        17)
          emerge =dev-lang/python-3.12.12
          use_params=python_single_target_python3_12 ;;
      esac
      echo ">llvm-runtimes/openmp-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvm-common-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-runtimes/compiler-rt-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-runtimes/compiler-rt-sanitizers-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/llvm-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      if [[ $(uname -m) == x86_64 ]] ; then
        echo ">llvm-core/llvmgold-${compiler_version%%\.*}-r9999" >> /etc/portage/package.mask/llvm
      fi
      echo ">llvm-core/llvm-toolchain-symlinks-${compiler_version%%\.*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/clang-common-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      echo ">llvm-core/clang-runtime-${compiler_version%%-r*}-r9999" >> /etc/portage/package.mask/llvm
      USE="libcxx $use_params" emerge =llvm-core/clang-${compiler_version}
      ln -s /usr/lib/llvm/${compiler_version%%.*}/bin/* /usr/local/bin/
    elif [[ ${compiler_kind} == gcc ]] ; then
      emerge --getbinpkgonly =sys-devel/gcc-${compiler_version}
      eselect gcc set ${GCC_TRIPLET}-${compiler_version%%\.*}
    else
      exit 1
    fi

    emerge app-arch/zip app-arch/unzip net-misc/curl app-misc/ca-certificates
    update-ca-certificates
    git clone --depth 1 https://github.com/microsoft/vcpkg.git /opt/vcpkg
    /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics
    ln -sf /opt/vcpkg/vcpkg /usr/local/bin/vcpkg

    rm -rf /var/db/repos/gentoo /var/cache/*
EOF

ENV VCPKG_ROOT=/opt/vcpkg
